version: '3'
services:
  database:
    container_name: database_container
    image: mongo:latest
    volumes:
      - /docker/volumes/census/data:/data/db
    expose:
      - 27017
    ports:
      - 27017:27017

  activemq:
    container_name: activemq_container
    image: rmohr/activemq:latest
    expose:
      - 61616
    ports:
      - 8161:8161
      - 61616:61616

  api-census-server:
    container_name: census_app_container
    build: .
    volumes:
      - ~/.m2:/root/.m2
    expose:
      - 8080
    ports:
      - 8080:9090
    command: mvn clean spring-boot:run